name: Output information
on: workflow_dispatch
jobs:
  print-env:
    runs-on: ubutu-latest
    steps:
      - name: Print envrionment variables
        run: env
  info:
    runs-on: ubutu-latest
    steps:
      - name: Output Github context
        run: echo "${{toJSON(github)}}"
