name: Test Workflow
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello .. you can use scripts here too"
      - name: Done Bye
        run: echo "Done ... Bye"
